categories = [
    {
        "name": "Trend Indicators",
        "description": "Indicators that identify market direction and trend strength",
        "indicators": [
            {
                "id": "moving_average",
                "name": "Moving Averages (Multiple)",
                "description": "Calculates both SMA and EMA for multiple periods",
                "types": ["SMA", "EMA"],
                "usage": "Crossovers indicate trend changes. Price above/below MA shows bullish/bearish bias",
                "parameters": {
                    "periods": {
                        "type": "array",
                        "default": [10, 20, 50, 100, 200],
                        "description": "Periods to calculate",
                    }
                },
                "output_columns": [
                    "SMA_10",
                    "SMA_20",
                    "SMA_50",
                    "EMA_10",
                    "EMA_20",
                    "EMA_50",
                ],
                "overlay": True,
            },
            {
                "id": "sma",
                "name": "Simple Moving Average",
                "description": "Arithmetic mean of closing prices over specified period",
                "usage": "Smooths price data to identify trend direction",
                "parameters": {
                    "length": {"type": "integer", "default": 20, "min": 1, "max": 500}
                },
                "output_columns": ["SMA_{length}"],
                "overlay": True,
            },
            {
                "id": "ema",
                "name": "Exponential Moving Average",
                "description": "Weighted moving average that gives more importance to recent prices",
                "usage": "More responsive to recent price changes than SMA",
                "parameters": {
                    "length": {"type": "integer", "default": 20, "min": 1, "max": 500}
                },
                "output_columns": ["EMA_{length}"],
                "overlay": True,
            },
            {
                "id": "macd",
                "name": "MACD",
                "description": "Moving Average Convergence Divergence - shows relationship between two EMAs",
                "usage": "Signal line crossovers indicate buy/sell signals. Histogram shows momentum strength",
                "parameters": {
                    "fast": {"type": "integer", "default": 12},
                    "slow": {"type": "integer", "default": 26},
                    "signal": {"type": "integer", "default": 9},
                },
                "output_columns": ["MACD", "MACDs", "MACDh"],
                "overlay": False,
            },
            {
                "id": "parabolic_sar",
                "name": "Parabolic SAR",
                "description": "Stop and Reverse - identifies potential reversal points",
                "usage": "Dots below price = uptrend, above price = downtrend",
                "parameters": {
                    "af": {
                        "type": "float",
                        "default": 0.02,
                        "description": "Acceleration factor",
                    },
                    "max_af": {
                        "type": "float",
                        "default": 0.2,
                        "description": "Maximum acceleration",
                    },
                },
                "output_columns": ["PSARl", "PSARs", "PSARaf", "PSARr"],
                "overlay": True,
            },
            {
                "id": "adx",
                "name": "ADX",
                "description": "Average Directional Index - measures trend strength",
                "usage": "ADX > 25 indicates strong trend, < 20 indicates weak trend",
                "parameters": {"length": {"type": "integer", "default": 14}},
                "output_columns": ["ADX", "DMP", "DMN"],
                "overlay": False,
            },
        ],
    },
    {
        "name": "Momentum Indicators",
        "description": "Measure the speed and strength of price movements",
        "indicators": [
            {
                "id": "rsi",
                "name": "RSI",
                "description": "Relative Strength Index - measures speed and change of price movements",
                "usage": "Overbought (>70), Oversold (<30). Divergences signal reversals",
                "parameters": {
                    "periods": {
                        "type": "array",
                        "default": [14],
                        "description": "RSI periods",
                    },
                    "length": {
                        "type": "integer",
                        "default": 14,
                        "alternative": "Single period mode",
                    },
                },
                "output_columns": ["RSI_14"],
                "overlay": False,
            },
            {
                "id": "stochastic",
                "name": "Stochastic Oscillator",
                "description": "Compares closing price to price range over time",
                "usage": "Overbought (>80), Oversold (<20). %K/%D crossovers signal trades",
                "parameters": {
                    "k_period": {"type": "integer", "default": 14},
                    "d_period": {"type": "integer", "default": 3},
                    "smooth_k": {"type": "integer", "default": 3},
                },
                "output_columns": ["STOCH_K", "STOCH_D"],
                "overlay": False,
            },
            {
                "id": "cci",
                "name": "CCI",
                "description": "Commodity Channel Index - identifies cyclical trends",
                "usage": "Above +100 = overbought, below -100 = oversold",
                "parameters": {"length": {"type": "integer", "default": 20}},
                "output_columns": ["CCI"],
                "overlay": False,
            },
            {
                "id": "williams_r",
                "name": "Williams %R",
                "description": "Momentum indicator measuring overbought/oversold levels",
                "usage": "Above -20 = overbought, below -80 = oversold",
                "parameters": {"length": {"type": "integer", "default": 14}},
                "output_columns": ["WILLR"],
                "overlay": False,
            },
        ],
    },
    {
        "name": "Volatility Indicators",
        "description": "Measure price fluctuation and market volatility",
        "indicators": [
            {
                "id": "bollinger_bands",
                "name": "Bollinger Bands",
                "description": "Volatility bands placed above and below moving average",
                "usage": "Squeeze indicates low volatility, expansion indicates high volatility. Price touching bands may signal reversals",
                "parameters": {
                    "length": {"type": "integer", "default": 20},
                    "std": {
                        "type": "float",
                        "default": 2.0,
                        "description": "Standard deviation multiplier",
                    },
                },
                "output_columns": ["BBU", "BBL", "BBM", "BB_Width", "BB_Pct"],
                "overlay": True,
            },
            {
                "id": "atr",
                "name": "ATR",
                "description": "Average True Range - measures market volatility",
                "usage": "Higher values = higher volatility. Used for stop-loss and position sizing",
                "parameters": {"length": {"type": "integer", "default": 14}},
                "output_columns": ["ATR"],
                "overlay": False,
            },
            {
                "id": "keltner_channels",
                "name": "Keltner Channels",
                "description": "Volatility-based envelope indicator using ATR",
                "usage": "Similar to Bollinger Bands but uses ATR instead of standard deviation",
                "parameters": {
                    "length": {"type": "integer", "default": 20},
                    "std": {
                        "type": "float",
                        "default": 2.0,
                        "description": "ATR multiplier",
                    },
                },
                "output_columns": ["KCU", "KCL", "KCM"],
                "overlay": True,
            },
        ],
    },
    {
        "name": "Volume Indicators",
        "description": "Analyze trading volume to confirm price movements",
        "indicators": [
            {
                "id": "obv",
                "name": "OBV",
                "description": "On Balance Volume - cumulative volume indicator",
                "usage": "Rising OBV confirms uptrend, falling OBV confirms downtrend. Divergences signal reversals",
                "parameters": {},
                "output_columns": ["OBV"],
                "overlay": False,
            },
            {
                "id": "vwap",
                "name": "VWAP",
                "description": "Volume Weighted Average Price",
                "usage": "Price above VWAP = bullish, below = bearish. Used by institutions",
                "parameters": {},
                "output_columns": ["VWAP"],
                "overlay": True,
            },
            {
                "id": "volume_profile",
                "name": "Volume Profile",
                "description": "Volume analysis and statistics",
                "usage": "Identifies volume trends and bullish/bearish volume distribution",
                "parameters": {"length": {"type": "integer", "default": 20}},
                "output_columns": [
                    "Volume_Change_Pct",
                    "Volume_Bullish",
                    "Volume_Bearish",
                    "Volume_MA",
                ],
                "overlay": False,
            },
        ],
    },
    {
        "name": "Support & Resistance",
        "description": "Identify key price levels where trends may pause or reverse",
        "indicators": [
            {
                "id": "pivot_points",
                "name": "Pivot Points",
                "description": "Calculate support/resistance levels based on previous period",
                "usage": "Price above pivot = bullish bias, below = bearish bias",
                "parameters": {
                    "timeperiod": {"type": "integer", "default": 1},
                    "levels": {
                        "type": "integer",
                        "default": 3,
                        "description": "Number of S/R levels",
                    },
                },
                "output_columns": ["pivot", "r1", "r2", "r3", "s1", "s2", "s3"],
                "overlay": True,
            },
            {
                "id": "fibonacci",
                "name": "Fibonacci Retracement",
                "description": "Automatic fibonacci retracement levels",
                "usage": "Key retracement levels: 23.6%, 38.2%, 50%, 61.8%, 78.6%",
                "parameters": {"length": {"type": "integer", "default": 50}},
                "output_columns": [
                    "Fib_0",
                    "Fib_236",
                    "Fib_382",
                    "Fib_500",
                    "Fib_618",
                    "Fib_786",
                    "Fib_100",
                ],
                "overlay": True,
            },
            {
                "id": "trendlines",
                "name": "Trendlines",
                "description": "Automated trendline fitting using linear regression",
                "usage": "Dynamic support/resistance levels based on price action",
                "parameters": {},
                "output_columns": [
                    "Support_Trendline",
                    "Resistance_Trendline",
                    "Distance_From_Support",
                    "Distance_From_Resistance",
                ],
                "overlay": True,
            },
            {
                "id": "support_resistance",
                "name": "S&R Levels",
                "description": "Detected support and resistance zones",
                "usage": "Price reactions at these levels indicate strength/weakness",
                "parameters": {"length": {"type": "integer", "default": 20}},
                "output_columns": ["Support_Level", "Resistance_Level"],
                "overlay": True,
            },
        ],
    },
    {
        "name": "Smart Money Concepts",
        "description": "Advanced institutional trading concepts and market structure analysis",
        "indicators": [
            {
                "id": "fvg",
                "name": "Fair Value Gaps",
                "description": "Price inefficiencies where institutional orders create imbalances",
                "usage": "FVGs act as magnetic price targets and support/resistance zones",
                "parameters": {},
                "output_columns": ["FVG", "FVG_Top", "FVG_Bottom"],
                "overlay": True,
            },
            {
                "id": "order_blocks",
                "name": "Order Blocks",
                "description": "Price zones where institutional orders are concentrated",
                "usage": "Price often returns to test these blocks before continuation",
                "parameters": {},
                "output_columns": ["OB", "OB_Top", "OB_Bottom"],
                "overlay": True,
            },
            {
                "id": "liquidity_zones",
                "name": "Liquidity Zones",
                "description": "Areas of clustered swing highs/lows indicating stop concentrations",
                "usage": "Price often sweeps these zones (stop hunts) before reversing",
                "parameters": {},
                "output_columns": ["Liquidity", "Liquidity_Level"],
                "overlay": True,
            },
            {
                "id": "break_of_structure",
                "name": "Break of Structure",
                "description": "Market structure breaks indicating trend continuation or reversal",
                "usage": "BOS confirms trend direction, CHoCH (Change of Character) indicates reversals",
                "parameters": {},
                "output_columns": ["BOS", "CHOCH"],
                "overlay": True,
            },
            {
                "id": "swing_highs_lows",
                "name": "Swing Highs/Lows",
                "description": "Identifies significant price turning points",
                "usage": "Foundation for market structure analysis and SMC concepts",
                "parameters": {"swing_length": {"type": "integer", "default": 5}},
                "output_columns": ["Swing_High", "Swing_Low"],
                "overlay": True,
            },
        ],
    },
    {
        "name": "Candlestick Patterns",
        "description": "Japanese candlestick pattern recognition for reversal and continuation signals",
        "indicators": [
            {
                "id": "heikin_ashi",
                "name": "Heikin-Ashi",
                "description": "Smoothed candlestick chart that filters market noise",
                "usage": "Easier trend identification. No wicks = strong trend",
                "parameters": {},
                "output_columns": ["HA_Open", "HA_High", "HA_Low", "HA_Close"],
                "overlay": False,
            },
            {
                "id": "doji",
                "name": "Doji",
                "description": "Indecision pattern with small body",
                "usage": "Potential reversal signal when appearing at trend extremes",
                "parameters": {},
                "output_columns": ["Doji"],
                "overlay": False,
            },
            {
                "id": "engulfing",
                "name": "Engulfing Pattern",
                "description": "Strong reversal pattern where current candle engulfs previous",
                "usage": "Bullish engulfing at bottoms, bearish engulfing at tops",
                "parameters": {},
                "output_columns": ["Bullish_Engulfing", "Bearish_Engulfing"],
                "overlay": False,
            },
            {
                "id": "hammer",
                "name": "Hammer",
                "description": "Bullish reversal pattern with long lower wick",
                "usage": "Appears at bottoms, signals potential upward reversal",
                "parameters": {},
                "output_columns": ["Hammer"],
                "overlay": False,
            },
            {
                "id": "shooting_star",
                "name": "Shooting Star",
                "description": "Bearish reversal pattern with long upper wick",
                "usage": "Appears at tops, signals potential downward reversal",
                "parameters": {},
                "output_columns": ["Shooting_Star"],
                "overlay": False,
            },
        ],
    },
    {
        "name": "Advanced Indicators",
        "description": "Complex multi-component indicators and cloud systems",
        "indicators": [
            {
                "id": "ichimoku",
                "name": "Ichimoku Cloud",
                "description": "Complete trend-following system with multiple components",
                "usage": "Price above cloud = bullish, below = bearish. Cloud thickness shows support/resistance strength",
                "parameters": {},
                "output_columns": ["ISA", "ISB", "ITS", "IKS", "ICS"],
                "overlay": True,
            }
        ],
    },
]
