"""
MetricInferenceManager
======================
Centralised singleton for metric-card model inference.

Mirrors AnalysisManager's singleton pattern (instantiated once in
metric_inference.py and shared across all requests).

Responsibilities
----------------
1. Load trained models + scalers from DB (with LRU in-memory cache).
2. Extract features from raw OHLCV candles using the same formulas as
   MetricFeatureEngineer / StockHeader.tsx.
3. Run model.predict() and format the result as a MetricPrediction.
4. Batch-predict all 4 metric cards in one call.

Feature parity guarantee
------------------------
The feature vector produced by ``extract_features()`` must be identical to
what was used during training (generated by MetricFeatureEngineer inside the
technical-analysis step).  Both use the same formulas and the same window
sizes (defaults: volatility_window=20, momentum_short=5, momentum_long=20).

Model storage
-------------
Models are stored in ``trained_models_analysis`` (model_binary BYTEA) and
scalers in the same row (scaler_binary BYTEA).  The ``metric_type`` column
(added by the phase20 migration) identifies which card the model serves.
``feature_names`` (JSONB) records the exact columns used during training so
inference can select the same subset.

Cache
-----
LRU eviction: once ``_cache_max_size`` models are loaded, the least-recently-
used entry is evicted before loading a new one.
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd

from app.database.connection import DbConfig, connect_with_retry

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

class MetricType(str, Enum):
    VOLATILITY = "volatility"
    SPEED      = "speed"
    DIRECTION  = "direction"
    REGIME     = "regime"


@dataclass
class MetricPrediction:
    """Single metric-card prediction result."""
    metric:          MetricType
    predicted_value: float          # raw numeric (% for vol/speed, 0/1 for dir/regime)
    predicted_label: str            # "15.34%" | "Bullish" | "Volatile"
    confidence:      float          # 0.0 – 1.0
    model_id:        str
    model_version:   str
    feature_importance: Optional[Dict[str, float]] = None
    timestamp:       str = field(default_factory=lambda: _utcnow_iso())


def _utcnow_iso() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# MetricInferenceManager
# ---------------------------------------------------------------------------

class MetricInferenceManager:
    """
    Singleton manager for metric-card model inference.

    Instantiated once at module load in ``metric_inference.py``::

        metric_inference_manager = MetricInferenceManager(db_config=db_config)

    Then used by route handlers::

        result = await metric_inference_manager.predict_metric(
            model_id, ohlcv_data, symbol, timeframe
        )
    """

    # Default feature extraction windows (must match MetricFeatureEngineer defaults)
    _DEFAULT_VOL_WINDOW       = 20
    _DEFAULT_REGIME_THRESHOLD = 2.0   # percent
    _DEFAULT_MOM_SHORT        = 5
    _DEFAULT_MOM_LONG         = 20
    _DEFAULT_SEQUENCE_LEN     = 60

    # Timeframe → integer index (for context embedding)
    _TF_INDEX: Dict[str, int] = {
        "M1": 0, "M5": 1, "M15": 2, "M30": 3,
        "H1": 4, "H4": 5, "D1": 6, "W1": 7, "MN1": 8,
    }

    def __init__(self, db_config: DbConfig, cache_max_size: int = 20):
        self.db_config = db_config
        self._cache_max_size = cache_max_size

        # model_id → loaded model object
        self._model_cache:    Dict[str, Any]   = {}
        # model_id → fitted scaler object (or None)
        self._scaler_cache:   Dict[str, Any]   = {}
        # model_id → metadata dict from DB
        self._metadata_cache: Dict[str, Dict]  = {}
        # model_id → last-access timestamp (for LRU)
        self._access_times:   Dict[str, float] = {}

        logger.info("MetricInferenceManager initialised")

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    async def predict_metric(
        self,
        model_id: str,
        ohlcv_data: List[Dict[str, Any]],
        symbol: str,
        timeframe: str,
    ) -> MetricPrediction:
        """
        Predict a single metric-card value.

        Flow:
          1. Load model + metadata (cached after first call).
          2. Extract features from *ohlcv_data*.
          3. Scale features using the stored scaler.
          4. Run model.predict().
          5. Format and return MetricPrediction.
        """
        meta  = await self._load_metadata(model_id)
        model = await self._load_model(model_id)

        metric_type = MetricType(meta.get("metric_type", "volatility"))
        feature_names: Optional[List[str]] = meta.get("feature_names")
        sequence_len: int = int(meta.get("sequence_length", self._DEFAULT_SEQUENCE_LEN))
        model_version: str = str(meta.get("version", "1"))

        # Feature extraction (CPU-bound → run in executor)
        loop = asyncio.get_running_loop()
        feature_vec = await loop.run_in_executor(
            None,
            lambda: self._extract_feature_vector(
                ohlcv_data, symbol, timeframe, sequence_len, feature_names
            ),
        )

        # Scale
        scaler = self._scaler_cache.get(model_id)
        if scaler is not None:
            try:
                feature_vec = scaler.transform(feature_vec.reshape(1, -1)).flatten()
            except Exception as scale_err:
                logger.warning(
                    f"[MetricInference] Scaler transform failed for {model_id[:8]}: "
                    f"{scale_err} – using raw features"
                )

        # Predict
        raw_value = await loop.run_in_executor(
            None,
            lambda: self._run_predict(model, feature_vec, metric_type),
        )

        label      = self._format_label(metric_type, raw_value)
        confidence = self._estimate_confidence(model, feature_vec, metric_type, raw_value)

        self._touch(model_id)

        return MetricPrediction(
            metric=metric_type,
            predicted_value=float(raw_value),
            predicted_label=label,
            confidence=float(confidence),
            model_id=model_id,
            model_version=model_version,
        )

    async def predict_all_metrics(
        self,
        model_ids: Dict[str, str],
        ohlcv_data: List[Dict[str, Any]],
        symbol: str,
        timeframe: str,
    ) -> Dict[str, MetricPrediction]:
        """
        Batch-predict all 4 metric cards in one call.

        *model_ids* is a dict mapping metric name → model UUID.
        Only metrics with a non-empty model_id are predicted.

        Returns a dict mapping metric name → MetricPrediction.
        """
        tasks = {
            metric: self.predict_metric(mid, ohlcv_data, symbol, timeframe)
            for metric, mid in model_ids.items()
            if mid and mid != "none"
        }
        results: Dict[str, MetricPrediction] = {}
        for metric, coro in tasks.items():
            try:
                results[metric] = await coro
            except Exception as exc:
                logger.error(
                    f"[MetricInference] predict_all_metrics failed for {metric}: {exc}"
                )
        return results

    def clear_cache(self, model_id: Optional[str] = None) -> None:
        """Clear model cache (all or a specific model)."""
        if model_id:
            for d in (self._model_cache, self._scaler_cache,
                      self._metadata_cache, self._access_times):
                d.pop(model_id, None)
            logger.info(f"[MetricInference] Cache cleared for model {model_id[:8]}")
        else:
            self._model_cache.clear()
            self._scaler_cache.clear()
            self._metadata_cache.clear()
            self._access_times.clear()
            logger.info("[MetricInference] Full cache cleared")

    # ------------------------------------------------------------------ #
    # Feature extraction                                                   #
    # ------------------------------------------------------------------ #

    def _extract_feature_vector(
        self,
        ohlcv_data: List[Dict[str, Any]],
        symbol: str,
        timeframe: str,
        sequence_len: int,
        feature_names: Optional[List[str]],
    ) -> np.ndarray:
        """
        Build a 1-D feature vector from raw OHLCV candles.

        Uses the same formulas as MetricFeatureEngineer so that inference
        features match training features exactly.
        """
        df = self._ohlcv_to_df(ohlcv_data)
        df = self._add_metric_columns(df)

        # Use the last *sequence_len* rows
        if len(df) > sequence_len:
            df = df.iloc[-sequence_len:]

        # If feature_names are stored, select exactly those columns
        if feature_names:
            available = [c for c in feature_names if c in df.columns]
            if available:
                df = df[available]
            else:
                logger.warning(
                    "[MetricInference] None of the stored feature_names found in "
                    "extracted DataFrame – using all metric columns"
                )
                df = df[[c for c in df.columns if c.startswith("metric_")]]
        else:
            # Fall back to all metric_* columns
            df = df[[c for c in df.columns if c.startswith("metric_")]]

        # Flatten to 1-D: (sequence_len × n_features,)
        arr = df.fillna(0).values.astype(np.float32)
        return arr.flatten()

    def _ohlcv_to_df(self, ohlcv_data: List[Dict[str, Any]]) -> pd.DataFrame:
        """Convert list-of-dicts to a normalised DataFrame."""
        df = pd.DataFrame(ohlcv_data)
        # Normalise column names to capitalised form
        rename = {}
        for col in df.columns:
            low = col.lower()
            if low in ("open", "high", "low", "close", "volume", "time", "date"):
                rename[col] = low.capitalize()
        if rename:
            df = df.rename(columns=rename)
        # Ensure numeric types
        for col in ("Open", "High", "Low", "Close", "Volume"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        return df

    def _add_metric_columns(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add metric_* columns using the same formulas as MetricFeatureEngineer.
        Kept inline here so inference has no dependency on the training-time class.
        """
        close = df["Close"].replace(0, np.nan)
        open_ = df["Open"].replace(0, np.nan)
        high  = df["High"]
        low   = df["Low"]

        # Base metrics
        df["metric_volatility"] = ((high - low) / close) * 100
        df["metric_speed"]      = ((close - open_).abs() / open_) * 100
        df["metric_direction"]  = (close > open_).astype(int)
        change_pct              = ((close - open_) / open_).abs() * 100
        df["metric_regime"]     = (change_pct > self._DEFAULT_REGIME_THRESHOLD).astype(int)

        # Rolling stats
        w = self._DEFAULT_VOL_WINDOW
        for metric in ("volatility", "speed"):
            s = df[f"metric_{metric}"]
            df[f"metric_{metric}_ma{w}"]  = s.rolling(w, min_periods=1).mean()
            df[f"metric_{metric}_std{w}"] = s.rolling(w, min_periods=2).std().fillna(0)

        df[f"metric_bullish_ratio{w}"]  = df["metric_direction"].rolling(w, min_periods=1).mean()
        df[f"metric_volatile_ratio{w}"] = df["metric_regime"].rolling(w, min_periods=1).mean()

        # Momentum
        s_win = self._DEFAULT_MOM_SHORT
        l_win = self._DEFAULT_MOM_LONG
        for metric in ("volatility", "speed"):
            s = df[f"metric_{metric}"]
            short_ma = s.rolling(s_win, min_periods=1).mean()
            long_ma  = s.rolling(l_win, min_periods=1).mean()
            ratio    = short_ma / long_ma.replace(0, np.nan)
            df[f"metric_{metric}_momentum"] = np.where(
                ratio > 1.2, 1.0, np.where(ratio < 0.8, -1.0, 0.0)
            )
            df[f"metric_{metric}_momentum_str"] = (
                (ratio - 1.0).abs().clip(0, 1) * 100
            ).fillna(0)

        return df

    # ------------------------------------------------------------------ #
    # Model loading                                                        #
    # ------------------------------------------------------------------ #

    async def _load_metadata(self, model_id: str) -> Dict:
        """Fetch model metadata from DB (cached)."""
        if model_id in self._metadata_cache:
            self._touch(model_id)
            return self._metadata_cache[model_id]

        meta = await self._fetch_model_metadata(model_id)
        if meta is None:
            raise ValueError(f"Model {model_id} not found in trained_models_analysis")

        self._metadata_cache[model_id] = meta
        return meta

    async def _load_model(self, model_id: str) -> Any:
        """Load model from DB with LRU cache."""
        if model_id in self._model_cache:
            self._touch(model_id)
            return self._model_cache[model_id]

        self._evict_lru_if_needed()

        model, scaler = await self._fetch_model_and_scaler(model_id)
        if model is None:
            raise ValueError(f"No model binary found for {model_id}")

        self._model_cache[model_id]  = model
        self._scaler_cache[model_id] = scaler  # may be None
        self._touch(model_id)
        return model

    async def _fetch_model_metadata(self, model_id: str) -> Optional[Dict]:
        """
        Query trained_models_analysis for lightweight metadata.
        Returns a dict with: metric_type, version, feature_names,
        sequence_length, training_data_symbol, training_data_timeframe.
        """
        try:
            conn = await connect_with_retry(self.db_config)
            try:
                row = await conn.fetchrow(
                    """
                    SELECT
                        model_id::text,
                        model_name,
                        version,
                        metric_type,
                        feature_names,
                        sequence_length,
                        training_data_symbol,
                        training_data_timeframe,
                        val_accuracy,
                        status
                    FROM trained_models_analysis
                    WHERE model_id = $1::uuid
                    """,
                    model_id,
                )
            finally:
                await conn.close()

            if row is None:
                return None

            feature_names = row["feature_names"]
            if isinstance(feature_names, str):
                try:
                    feature_names = json.loads(feature_names)
                except Exception:
                    feature_names = None

            return {
                "model_id":                 row["model_id"],
                "model_name":               row["model_name"],
                "version":                  str(row["version"] or 1),
                "metric_type":              row["metric_type"] or "volatility",
                "feature_names":            feature_names,
                "sequence_length":          row["sequence_length"] or self._DEFAULT_SEQUENCE_LEN,
                "training_data_symbol":     row["training_data_symbol"],
                "training_data_timeframe":  row["training_data_timeframe"],
                "val_accuracy":             float(row["val_accuracy"] or 0),
                "status":                   row["status"],
            }
        except Exception as exc:
            logger.error(f"[MetricInference] _fetch_model_metadata failed: {exc}")
            return None

    async def _fetch_model_and_scaler(
        self, model_id: str
    ) -> Tuple[Optional[Any], Optional[Any]]:
        """
        Load model_binary and scaler_binary from trained_models_analysis.
        Deserialises both and returns (model, scaler).
        """
        try:
            conn = await connect_with_retry(self.db_config)
            try:
                row = await conn.fetchrow(
                    """
                    SELECT model_binary, scaler_binary
                    FROM trained_models_analysis
                    WHERE model_id = $1::uuid
                    """,
                    model_id,
                )
            finally:
                await conn.close()

            if row is None or not row["model_binary"]:
                logger.warning(f"[MetricInference] No binary found for model {model_id[:8]}")
                return None, None

            model  = self._deserialise_model(row["model_binary"])
            scaler = self._deserialise_scaler(row["scaler_binary"]) if row["scaler_binary"] else None
            return model, scaler

        except Exception as exc:
            logger.error(f"[MetricInference] _fetch_model_and_scaler failed: {exc}")
            return None, None

    # ------------------------------------------------------------------ #
    # Deserialisation helpers                                              #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _deserialise_model(binary: bytes) -> Optional[Any]:
        """Try TensorFlow HDF5 first, then joblib/pickle."""
        # TensorFlow HDF5
        try:
            import tensorflow as tf
            buf = io.BytesIO(binary)
            return tf.keras.models.load_model(buf)
        except Exception:
            pass
        # joblib / pickle fallback
        try:
            buf = io.BytesIO(binary)
            return joblib.load(buf)
        except Exception as exc:
            logger.error(f"[MetricInference] Model deserialisation failed: {exc}")
            return None

    @staticmethod
    def _deserialise_scaler(binary: bytes) -> Optional[Any]:
        """Deserialise a joblib-serialised scaler."""
        try:
            buf = io.BytesIO(binary)
            return joblib.load(buf)
        except Exception as exc:
            logger.warning(f"[MetricInference] Scaler deserialisation failed: {exc}")
            return None

    # ------------------------------------------------------------------ #
    # Prediction helpers                                                   #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _run_predict(model: Any, feature_vec: np.ndarray, metric_type: MetricType) -> float:
        """
        Run model.predict() and extract a scalar output.
        Handles both Keras models and sklearn-style estimators.
        """
        X = feature_vec.reshape(1, -1)

        # Keras / TensorFlow
        if hasattr(model, "predict") and hasattr(model, "layers"):
            try:
                pred = model.predict(X, verbose=0)
                val  = float(np.squeeze(pred))
                # Sigmoid output → probability for classification
                if metric_type in (MetricType.DIRECTION, MetricType.REGIME):
                    return float(np.clip(val, 0.0, 1.0))
                return val
            except Exception as exc:
                logger.warning(f"[MetricInference] Keras predict failed: {exc}")

        # sklearn-style
        if hasattr(model, "predict_proba"):
            try:
                proba = model.predict_proba(X)
                return float(proba[0, 1])   # probability of class 1
            except Exception:
                pass
        if hasattr(model, "predict"):
            try:
                return float(model.predict(X)[0])
            except Exception as exc:
                logger.warning(f"[MetricInference] sklearn predict failed: {exc}")

        return 0.0

    @staticmethod
    def _estimate_confidence(
        model: Any,
        feature_vec: np.ndarray,
        metric_type: MetricType,
        raw_value: float,
    ) -> float:
        """
        Estimate prediction confidence.

        For classification: distance of probability from 0.5 → [0.5, 1.0].
        For regression: fixed 0.75 (no calibration without validation set).
        sklearn models with predict_proba return max class probability.
        """
        if metric_type in (MetricType.DIRECTION, MetricType.REGIME):
            # raw_value is already a probability [0, 1]
            return float(abs(raw_value - 0.5) * 2)   # maps [0.5,1] → [0,1]

        # Regression: try predict_proba if available (unlikely), else fixed
        if hasattr(model, "predict_proba"):
            try:
                X     = feature_vec.reshape(1, -1)
                proba = model.predict_proba(X)
                return float(np.max(proba))
            except Exception:
                pass
        return 0.75

    @staticmethod
    def _format_label(metric_type: MetricType, raw_value: float) -> str:
        """Convert raw model output to the display string the frontend expects."""
        if metric_type == MetricType.VOLATILITY:
            return f"{raw_value:.2f}%"
        if metric_type == MetricType.SPEED:
            return f"{raw_value:.2f}%"
        if metric_type == MetricType.DIRECTION:
            return "Bullish" if raw_value >= 0.5 else "Bearish"
        if metric_type == MetricType.REGIME:
            return "Volatile" if raw_value >= 0.5 else "Stable"
        return str(round(raw_value, 4))

    # ------------------------------------------------------------------ #
    # LRU cache management                                                 #
    # ------------------------------------------------------------------ #

    def _touch(self, model_id: str) -> None:
        self._access_times[model_id] = time.monotonic()

    def _evict_lru_if_needed(self) -> None:
        """Evict the least-recently-used model if the cache is full."""
        if len(self._model_cache) < self._cache_max_size:
            return
        lru_id = min(self._access_times, key=self._access_times.get)
        self.clear_cache(lru_id)
        logger.info(f"[MetricInference] LRU evicted model {lru_id[:8]}")
